// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR0Vzr0BaSNpQ1WUPRwZXn4yarGkNQLOE',
    appId: '1:337559412891:web:319682b33e2bbfc3cd263e',
    messagingSenderId: '337559412891',
    projectId: 'clavedosul-43866',
    authDomain: 'clavedosul-43866.firebaseapp.com',
    databaseURL: 'https://clavedosul-43866-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'clavedosul-43866.appspot.com',
    measurementId: 'G-HQHWSHH7XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpg4YT3HgWxYobIPIr9JqSLRvYEzd2c4',
    appId: '1:337559412891:android:0d183ce23b2c406ecd263e',
    messagingSenderId: '337559412891',
    projectId: 'clavedosul-43866',
    databaseURL: 'https://clavedosul-43866-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'clavedosul-43866.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg1bP1mAE9DRxvkUURCNBsMxcKNLL9gTY',
    appId: '1:337559412891:ios:65ead7c4294e1d04cd263e',
    messagingSenderId: '337559412891',
    projectId: 'clavedosul-43866',
    databaseURL: 'https://clavedosul-43866-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'clavedosul-43866.appspot.com',
    iosClientId: '337559412891-kucv20frci80lmfkfjlor5lp1c30dm1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.rockSchoolManagerFrontend',
  );
}
